# Generated by Django 3.0.8 on 2021-01-13 21:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('rich_text', wagtail.core.blocks.RichTextBlock(label='Text'))], blank=True),
        ),
        migrations.AlterField(
            model_name='newpage',
            name='body',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('rich_text', wagtail.core.blocks.RichTextBlock(label='Text'))], blank=True),
        ),
    ]
