# Generated by Django 3.0.8 on 2021-01-26 20:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0003_auto_20210113_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock(label='Raw HTML')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('rich_text', wagtail.core.blocks.RichTextBlock(label='Text'))], blank=True),
        ),
        migrations.DeleteModel(
            name='NewPage',
        ),
    ]
